package com.mehdiii.duelgame.models.base;

/**
 * Created by omid on 4/22/2015.
 */
public enum CommandType {
    UNKNOWN,
    SEND_GET_PROVINCE_RANK,
    SEND_GET_FRIENDS_RANK,
    SEND_GET_TOTAL_RANK,
    RECEIVE_GET_PROVINCE_RANK,
    RECEIVE_GET_FRIENDS_RANK,
    RECEIVE_GET_TOTAL_RANK,
    SEND_REGISTER,
    RECEIVE_LOGIN_INFO,
    SEND_GET_FRIEND_LIST,
    RECEIVE_GET_FRIEND_LIST,
    RECEIVE_ASK_NEXT_QUESTION,
    RECEIVE_OPPONENT_SCORE,
    RECEIVE_GAME_ENDED,
    SEND_START_PURCHASE,
    SEND_PURCHASE_DIAMOND,
    RECEIVE_START_PURCHASE,
    SEND_PURCHASE_DONE,
    RECEIVE_PURCHASE_DONE,
    RECEIVE_OPPONENT_INFO,
    RECEIVE_GAME_DATA,
    RECEIVE_START_PLAYING,
    RECEIVE_FRIEND_LIST,
    SEND_ADD_FRIEND,
    RECEIVE_ADD_FRIEND,
    SEND_FRIEND_REQUEST_RESPONSE,
    SEND_UPDATE_SETTINGS,
    RECEIVE_UPDATE_SETTINGS,
    SEND_USER_LEFT_GAME,
    SEND_GET_QUESTION,
    SEND_WANNA_PLAY,
    SEND_USER_LOGIN_REQUEST,
    SEND_READY_TO_PLAY,
    RECEIVE_OPPONENT_DATA,
    SEND_WANNA_CHALLENGE,
    RECEIVE_CHALLENGE_REQUEST
}
